name: fish-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - notebook
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - ipywidgets
  - tqdm
  - requests
  - imageio
  - h5py
  - scipy
  - openpyxl
  - pip
  - pip:
      - caveclient
      - brainrender
      - cloud-volume
